channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain
    - langchain-core
    - langchain-community
    - pypdf==3.17.1
    - tiktoken==0.5.1
    - langgraph==0.0.15
    - beautifulsoup4==4.12.2
    - python-dotenv==1.0.0
    - langchain-mistralai
    - streamlit==1.24.0
    - pandas
    - pandasai
    - numpy==1.24.3
    - mistralai
    - python-magic==0.4.27
    - pydantic>=2.5.2,<3.0.0
